version: '3.4'

services:
  postgres:
    image: postgis/postgis:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: streetsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  streetservice:
      build:
        context: ../StreetService
        dockerfile: Dockerfile
      ports:
        - "5001:5001"
      environment:
        - ASPNETCORE_ENVIRONMENT=Development # enables Swagger UI
        - ASPNETCORE_URLS=http://+:80;http://+:5001 # tells app which urls to listen on, fallback to 80 if 5001 is not available
        - CONNECTION_STRING="Host=postgres;Database=streetsdb;Username=postgres;Password=mysecretpassword;"
      depends_on:
        - postgres

volumes:
  postgres-data:
  pgadmin-data: